### ISSUE TITLE
Retrieve and decrypt fail

### ISSUE THREAD

**Issue by JeffersonJefferson-pixel** [nucypher/nucypher-ts-demo#3]
I might be giving wrong configurations but I just can't seem to get the demo to work.

At first, the default porter uri (https://porter-ibex.nucypher.community) doesn't work. So i ran my own porter on localhost. I managed to get porter running with this configuration.

![image](https://user-images.githubusercontent.com/70904744/202061304-522e11c5-2c8f-4d68-ba51-343072717cbc.png)

I managed to get it to working until the "retrieve and decrypt" step but following error occurred.

![image](https://user-images.githubusercontent.com/70904744/202062461-27652a23-9b7b-4752-9996-066ba2aab216.png)

Thanks in advance for any help.

**Comment by piotr-roslaniec** [comment]
Hi @JeffersonJefferson-pixel.  

Could you share the contents of the network request that caused this error? And possibly the contents of the HTTP 400 response. You can find it by opening the "Network" tab in developer tools in your browser.

**Comment by JeffersonJefferson-pixel** [comment]
Here are the contents of the request/response

- request
![image](https://user-images.githubusercontent.com/70904744/202125127-b345164b-2b07-4ebb-8878-69bc56820be7.png)

- payload
![image](https://user-images.githubusercontent.com/70904744/202125180-c1f3658d-3e13-4a8b-976a-2d348057572e.png)

- response
![image](https://user-images.githubusercontent.com/70904744/202125237-70b42597-291a-421c-a5c6-808df8f13f77.png)

thank you, @piotr-roslaniec.

**Comment by piotr-roslaniec** [comment]
@JeffersonJefferson-pixel Could you also share the `nucypher-ts` version you're using? Thanks.

**Comment by JeffersonJefferson-pixel** [comment]
The version is `0.8.1`.

On a side note, i configured the porter to connect to tapir (Goerli) but the demo runs on Mumbai. Could this be the cause of the problem?

Thanks.

**Comment by JeffersonJefferson-pixel** [comment]
i look at an example retrieve_cfrags request to porter at https://docs.nucypher.com/en/latest/application_development/web_development.html#run-porter-directly

![image](https://user-images.githubusercontent.com/70904744/202135961-c2f3bbc3-9b6d-4264-af3a-b12b0b6388c3.png)

It seems one field (policy_encrypting_key) is missing

edit: never mind, the field is actually not expected

**Comment by jdbertron** [comment]
This is related to https://github.com/nucypher/nucypher/issues/3006   .
By the way, it should now be porter-tapir not porter-ibex, which has been taken down.

**Comment by JeffersonJefferson-pixel** [comment]
For the deployed example on https://nucypher-ts-demo.netlify.app/, i used porter-tapir (https://porter-tapir.nucypher.community), there is a cors error and a 404 response during the decrypt step.

To get around the cors error, I thought to test on local machine where I changed the `nuypher-ts` version to 0.7.9-alpha.26, and ran `nucypher-porter` container built from its main branch. I think both use `nucypher-core` 0.4.0. but i don't know whether ursula nodes running on tapir network has a `nucypher` that uses the same version of `nucypher-core` . Anyway, the original problem still persists.

- The cors error and 404 response on deployed example:

![image](https://user-images.githubusercontent.com/70904744/202402644-fbf78d0b-4cb5-4cb7-8ca2-9fb3466f709b.png)

![image](https://user-images.githubusercontent.com/70904744/202402923-526d9985-a548-4667-bd7a-6691c2df5af6.png)

![image](https://user-images.githubusercontent.com/70904744/202403036-064b34cd-25d4-4944-b98c-b515ec64a746.png)

- nucypher-ts config used for local testing:

![image](https://user-images.githubusercontent.com/70904744/202405451-05bc4aeb-6773-4895-8eed-bdfe810034c9.png)

**Comment by JeffersonJefferson-pixel** [comment]
To control version on ursula nodes, I also tried running federated ursula nodes on local machine using `nucypher` development branch. I think this also use `nucypher-core` 0.4.0. I then ran a nucypher-porter with following config

![image](https://user-images.githubusercontent.com/70904744/202409626-a18d42d0-d51b-4683-8f63-a6bf03cce733.png)

The same problem also occurred.

**Comment by JeffersonJefferson-pixel** [comment]
Just an update, if i used the public tapir porter (https://porter-tapir.nucypher.community) for local testing, there is no cors error and the original problem is also solved. The same is also true for the deployed example.

![image](https://user-images.githubusercontent.com/70904744/202612877-8708e2d1-ef30-426c-8823-b15f5e59199f.png)
